language: ruby
#script: 'bundle exec rake db:migrate'
script: 'bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:test:prepare && bundle exec rspec spec/'
rvm:
  - 2.0.0
env:
notifications:
  email:
    team@getkandan.com
# whitelist
branches:
  only:
    - master
